### ISSUE TITLE
laravel/framework replaces illuminate/support and thus cannot coexist with it

### ISSUE THREAD

**Issue by ShaunWilders** [emotality/laravel-color#1]
"illuminate/support": "^8.0|^9.0|^10.0" in composer.json isn't allowing installation of the latest version of this package in Laravel 11 as it was replaced with laravel/framework. Laravel 9+ also requires PHP v8+.

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.12) does not satisfy that requirement.
    - Root composer.json requires emotality/laravel-color ^1.2 -> satisfiable by emotality/laravel-color[1.2.0, 1.2.1].   
    - Conclusion: don't install laravel/framework v11.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.1 (conflict analysis result)
    - emotality/laravel-color[1.2.0, ..., 1.2.1] require illuminate/support ^8.0|^9.0|^10.0 -> satisfiable by illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.8].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.8, v11.0.0, ..., v11.4.0], laravel/framework[v11.0.0, ..., v11.4.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.4.0].

**Comment by emotality** [comment]
Added Laravel 11 support.

And PHP is `>=7.3` not `^7.3` which means anything higher than `7.3.0` will work, even `7.4`, `8.1` and `8.3` etc.

```json
"require": {
  "php": ">=7.3",
  "ext-json": "*",
  "ext-bcmath": "*",
  "illuminate/support": "^8.0|^9.0|^10.0|^11.0"
},
```

Thanks 😊
